/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import common.MenuEnum;
import controller.Navigator;
import dto.MenuDto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author qphan
 */
public class FrMain extends javax.swing.JFrame {

    /**
     * Creates new form HomePageJFrame
     */
    public FrMain() {
        initComponents();
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        final Navigator navigator = new Navigator(pnMainView);
        navigator.viewPage(new PnStudentManager());
        
        final List<MenuDto> menus = new ArrayList<>();
        menus.add(new MenuDto(MenuEnum.HomePage, pnHomePage, lbHomePage));
        menus.add(new MenuDto(MenuEnum.StudentManager, pnStudentMan, lbStudentMan));
        menus.add(new MenuDto(MenuEnum.CourseManager, pnCourseMan, lbCourseMan));
        menus.add(new MenuDto(MenuEnum.StatisticalManager, pnThongKe, lbThongKe));
        
        navigator.addEventListeners(menus);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnLeft = new javax.swing.JPanel();
        pnApp = new javax.swing.JPanel();
        lbApp = new javax.swing.JLabel();
        pnLeftMenu = new javax.swing.JPanel();
        pnHomePage = new javax.swing.JPanel();
        lbHomePage = new javax.swing.JLabel();
        pnStudentMan = new javax.swing.JPanel();
        lbStudentMan = new javax.swing.JLabel();
        pnCourseMan = new javax.swing.JPanel();
        lbCourseMan = new javax.swing.JLabel();
        pnGradeMan = new javax.swing.JPanel();
        lbGradeMan = new javax.swing.JLabel();
        pnThongKe = new javax.swing.JPanel();
        lbThongKe = new javax.swing.JLabel();
        pnMainView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnLeft.setBackground(new java.awt.Color(0, 0, 0));
        pnLeft.setLayout(new java.awt.BorderLayout());

        pnApp.setBackground(new java.awt.Color(255, 51, 0));
        pnApp.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 10));

        lbApp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbApp.setForeground(new java.awt.Color(255, 255, 255));
        lbApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_ung_dung_white_24dp.png"))); // NOI18N
        lbApp.setText("QUẢN LÝ HỌC VIÊN");
        pnApp.add(lbApp);

        pnLeft.add(pnApp, java.awt.BorderLayout.NORTH);

        pnLeftMenu.setBackground(new java.awt.Color(0, 0, 0));
        pnLeftMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 1, 15));
        pnLeftMenu.setLayout(new java.awt.GridLayout(8, 0, 0, 10));

        pnHomePage.setBackground(new java.awt.Color(96, 100, 191));
        pnHomePage.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnHomePage.setPreferredSize(new java.awt.Dimension(260, 90));
        pnHomePage.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 20));

        lbHomePage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbHomePage.setForeground(new java.awt.Color(255, 255, 255));
        lbHomePage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_menu0_white_24dp.png"))); // NOI18N
        lbHomePage.setText("MÀN HÌNH CHÍNH");
        pnHomePage.add(lbHomePage);

        pnLeftMenu.add(pnHomePage);

        pnStudentMan.setBackground(new java.awt.Color(76, 175, 80));
        pnStudentMan.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 20));

        lbStudentMan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbStudentMan.setForeground(new java.awt.Color(255, 255, 255));
        lbStudentMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_menu1_white_24dp.png"))); // NOI18N
        lbStudentMan.setText("QUẢN LÝ HỌC VIÊN");
        pnStudentMan.add(lbStudentMan);

        pnLeftMenu.add(pnStudentMan);

        pnCourseMan.setBackground(new java.awt.Color(76, 175, 80));
        pnCourseMan.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 20));

        lbCourseMan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbCourseMan.setForeground(new java.awt.Color(255, 255, 255));
        lbCourseMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_menu2_white_24dp.png"))); // NOI18N
        lbCourseMan.setText("QUẢN LÝ KHÓA HỌC");
        pnCourseMan.add(lbCourseMan);

        pnLeftMenu.add(pnCourseMan);

        pnGradeMan.setBackground(new java.awt.Color(76, 175, 80));
        pnGradeMan.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 20));

        lbGradeMan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbGradeMan.setForeground(new java.awt.Color(255, 255, 255));
        lbGradeMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_menu3_white_24dp.png"))); // NOI18N
        lbGradeMan.setText("QUẢN LÝ LỚP HỌC");
        pnGradeMan.add(lbGradeMan);

        pnLeftMenu.add(pnGradeMan);

        pnThongKe.setBackground(new java.awt.Color(76, 175, 80));
        pnThongKe.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 20));

        lbThongKe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbThongKe.setForeground(new java.awt.Color(255, 255, 255));
        lbThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_menu4_white_24dp.png"))); // NOI18N
        lbThongKe.setText("THỐNG KÊ DỮ LIỆU");
        pnThongKe.add(lbThongKe);

        pnLeftMenu.add(pnThongKe);

        pnLeft.add(pnLeftMenu, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnLeft, java.awt.BorderLayout.WEST);

        javax.swing.GroupLayout pnMainViewLayout = new javax.swing.GroupLayout(pnMainView);
        pnMainView.setLayout(pnMainViewLayout);
        pnMainViewLayout.setHorizontalGroup(
            pnMainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );
        pnMainViewLayout.setVerticalGroup(
            pnMainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 874, Short.MAX_VALUE)
        );

        getContentPane().add(pnMainView, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbApp;
    private javax.swing.JLabel lbCourseMan;
    private javax.swing.JLabel lbGradeMan;
    private javax.swing.JLabel lbHomePage;
    private javax.swing.JLabel lbStudentMan;
    private javax.swing.JLabel lbThongKe;
    private javax.swing.JPanel pnApp;
    private javax.swing.JPanel pnCourseMan;
    private javax.swing.JPanel pnGradeMan;
    private javax.swing.JPanel pnHomePage;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnLeftMenu;
    private javax.swing.JPanel pnMainView;
    private javax.swing.JPanel pnStudentMan;
    private javax.swing.JPanel pnThongKe;
    // End of variables declaration//GEN-END:variables
}
